<?php
/**
 * @file
 * Provides a block with an alternative URL-based breadcrumb trail.
 */

/**
 * Implements hook_config_info().
 */
function easy_breadcrumb_config_info() {
  $prefixes['easy_breadcrumb.settings'] = array(
    'label' => t('System performance'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_permission().
 */
function easy_breadcrumb_permission() {
  return array(
    'administer easy_breadcrumb' => array(
      'title' => t('Administer Easy Breadcrumb'),
      'description' => t('Perform administration tasks for the module Easy Breadcrumb.'),
    ),
  );
}

/**
 * Implements hook_init().
 *
 * @todo See if we have a breadcrumb_alter or similar. This is expensive.
 */
function easy_breadcrumb_init() {
  global $theme;
  $site_theme = config_get('system.core', 'theme_default');
  $admin_theme = config_get('system.core', 'admin_theme');

  // Disable admin theme breadcrumb, but only if different than default theme.
  if ($theme === $admin_theme && $site_theme !== $admin_theme) {
    $disable_admin_breadcrumb = config_get('easy_breadcrumb.settings', 'disable_admin_breadcrumb');
    if ($disable_admin_breadcrumb) {
      // Sets the default breadcrumb to an empty array to disable it.
      backdrop_set_breadcrumb(array());
    }
  }
  // Disable default theme breadcrumbs.
  else {
    $disable_default_breadcrumb = config_get('easy_breadcrumb.settings', 'disable_default_breadcrumb');
    if ($disable_default_breadcrumb) {
      // Sets the default breadcrumb to an empty array to disable it.
      backdrop_set_breadcrumb(array());
    }
  }
}

/**
 * Implements hook_menu().
 */
function easy_breadcrumb_menu() {
  $items = array();
  $items['admin/config/user-interface/easy-breadcrumb'] = array(
    'title' => 'Easy Breadcrumb',
    'description' => "Controls settings for the module Easy Breadcrumb",
    'file' => 'easy_breadcrumb.admin.inc',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('easy_breadcrumb_settings_form'),
    'access arguments' => array('administer easy_breadcrumb'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function easy_breadcrumb_theme($existing, $type, $theme, $path) {
  return array(
    'easy_breadcrumb' => array(
      'variables' => array(
        'breadcrumb' => NULL,
        'segments_quantity' => NULL,
        'separator' => NULL,
        'separator_ending' => NULL,
      ),
      'template' => 'easy-breadcrumb',
      'path' => backdrop_get_path('module', 'easy_breadcrumb') . '/templates',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function easy_breadcrumb_block_info() {
  $block = array();
  $block['easy_breadcrumb'] = array(
    'info' => t('Easy Breadcrumb'),
    'description' => t('Replacement for the system breadcrumb block.'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $block;
}

/**
 * Implements hook_block_view().
 */
function easy_breadcrumb_block_view($delta = NULL) {
  $block = array();
  switch ($delta) {
    case 'easy_breadcrumb':
      $block['subject'] = NULL;
      $block['content'] = theme('easy_breadcrumb');
      break;
  }
  return $block;
}

/**
 * Process variables for easy-breadcrumb.tpl.php.
 *
 * @see easy-breadcrumb.tpl.php
 */
function template_preprocess_easy_breadcrumb(&$variables) {
  $breadcrumbs = _easy_breadcrumb_build_items();
  $variables['list_type'] = 'https://schema.org/BreadcrumbList';
  foreach ($breadcrumbs as $i => $breadcrumb) {
    if (isset($breadcrumb['url'])) {
      $variables['breadcrumb'][$i] = '<span>';

      $parsed_query = array();
      $parsed_url = parse_url($breadcrumb['url']);
      if (isset($parsed_url['query'])) {
        parse_str($parsed_url['query'], $parsed_query);
      }
      $variables['breadcrumb'][$i] .= l('<span itemprop="name">' . $breadcrumb['content'] . '</span>', $parsed_url['path'], array(
        'attributes' => array(
          'class' => $breadcrumb['class'],
          'itemtype' => "http://schema.org/Thing",
          'itemprop' => "item",
          'itemscope' => "",
          'itemid' => check_plain(url($breadcrumb['url'], array('absolute' => TRUE,))),
        ),
        'query' => $parsed_query,
        'html' => (!empty($breadcrumb['html'])) ? $breadcrumb['html'] : FALSE,
      ));

      $variables['breadcrumb'][$i] .= '</span>';
    }
    else {
      $class = implode(' ', $breadcrumb['class']);
      $variables['breadcrumb'][$i] = '<span class="' . $class . '" itemprop="name">' . $breadcrumb['content'] . '</span>';
    }
  }
  $variables['segments_quantity'] = isset($variables['breadcrumb']) ? count($variables['breadcrumb']) : 0;
  $config = config('easy_breadcrumb.settings');
  $variables['separator_ending'] = $config->get('separator_end');
  $variables['separator'] = filter_xss($config->get('separator'));
}

/**
 * Helper function to generate breadcrumb items.
 *
 * @return array
 *   Items of the breadcrumb.
 */
function _easy_breadcrumb_build_items() {
  $config = config('easy_breadcrumb.settings');
  // Array storing the breadcrumb's segments.
  $breadcrumb = array();
  // Default classes for the segments.
  $segments_classes = array('crumb');
  // Gets the flag saying if the front page segment should be included.
  $include_front_page_segment = $config->get('include_home');

  // Conditionally include the front page segment in the breadcrumb.
  if ($include_front_page_segment) {
    $front_text = _easy_breadcrumb_obtain_home_title();
    // Marks the front--segment with an identifier class (useful for CSS).
    $segments_classes[1] = 'crumb-front';
    // Adds a segment for the front page.
    $breadcrumb[] = _easy_breadcrumb_build_item($front_text, $segments_classes, '<front>');
  }

  // There won't be more segments if visiting the front page, the don't waste resources.
  if (!backdrop_is_front_page()) {

    // Gets the flag saying the capitalizator mode.
    $capitalizator_mode = $config->get('caps_mode');

    // List of words to be ignored by the capitalizator.
    $capitalizator_ignored_words = $config->get('caps_ignored_words');

    // Flag for including invalid paths as plain-text segments.
    $include_invalid_paths = $config->get('include_invalid_paths');

    // List of path to be excluded while generating segments.
    $excluded_paths_arr = $config->get('excluded_paths');

    // Obtains the alias of the current path.
    $alias = backdrop_get_path_alias();

    // We need to pass our path through hook_url_outbound_alter(). This fixes
    // clean URLs not working when they don't exist in the {url_alias} table and
    // are created with something like subpathauto.
    $normalized_path = current_path();

    // hook_url_outbound_alter() expects defaults in url() options.
    $options = array(
      'fragment' => '',
      'query' => array(),
      'absolute' => FALSE,
      'alias' => FALSE,
      'prefix' => '',
      'external' => FALSE,
    );

    backdrop_alter('url_outbound', $alias, $options, $normalized_path);

    // Allow the alias to be altered.
    backdrop_alter('easy_breadcrumb_path', $alias);


    // Get the segments of the current path.
    $alias_arr = explode('/', $alias);

    // Get the quantity of segments in the current path.
    $segments_quantity = count($alias_arr);

    $segment_url_arr = array();

    // Iterates over the segments of the current URL
    // ("blog/article/hello-world") excepting the last segment
    // (the title, 'hello-world' in that case).
    $last_segment_title = '';
    for ($idx_0 = 0, $idx_1 = 1; $idx_1 < $segments_quantity; ++$idx_0, ++$idx_1) {
      // Build an array containing the URL of the segment being currently
      // processed. E.g., having $alias as "blog/article/hello-world", at the
      // first iteration this array will be array('blog'), the second
      // (and last in that case) the array will be array('blog','article').
      $segment_url_arr[] = $alias_arr[$idx_0];
      // String with the potential-path of the segment being processed (e.g. 'blog/article').
      $segment_url = implode('/', $segment_url_arr);

      // Jump to the next segment if this url is configured to be excluded.
      $excluded_path = _easy_breadcrumb_check_excluded_path($segment_url);
      if ($excluded_path) {
        continue;
      }

      $segments_classes[1] = 'crumb-' . $idx_1;
      // Obtain the internal path it represents.
      $segment_normal_path = backdrop_get_normal_path($segment_url);

      // Check if this is a valid path.
      $segment_valid_path = _easy_breadcrumb_validate_segment_path($segment_normal_path);

      // Get the segment's raw text from the URL.
      $segment_text = $alias_arr[$idx_0];
      // Normalized segment's text (e.g. 'Blog');
      $segment_title = _easy_breadcrumb_obtain_segment_title($segment_normal_path, $segment_valid_path, $segment_text);
      _easy_breadcrumb_check_replaced_title($segment_title);

      // Don't duplicate breadcrumbs for menu default local tasks.
      if ($segment_title == $last_segment_title) {
        $item = menu_get_item($segment_url);
        if ($item['type'] != MENU_VISIBLE_IN_BREADCRUMB) {
          continue;
        }
      }

      if ($segment_valid_path || $include_invalid_paths) {
        $breadcrumb[] = _easy_breadcrumb_build_item($segment_title, $segments_classes, $segment_url, $segment_valid_path);
      }
      $last_segment_title = $segment_title;
    }

    // Gets the flag saying if the title should be appended to the breadcrumb.
    $include_page_title_segment = $config->get('include_title');

    // Adds the page's title to the breadcrumb.
    if ($include_page_title_segment && (arg(0) != 'user')) {
      // Marks the page's-title-segment with an identifier class (useful for CSS).
      $segments_classes[1] = 'crumb-title';
      // The title is the last segment in the URL.
      $segment_text = $alias_arr[$segments_quantity - 1];
      $segment_title = _easy_breadcrumb_obtain_page_title($segment_text);

      _easy_breadcrumb_check_replaced_title($segment_title);

      $title_segment_as_link = $config->get('title_link');
      // If the page's title will be a link or just a text.
      $breadcrumb[] = _easy_breadcrumb_build_item($segment_title, $segments_classes, $alias, $title_segment_as_link);
    }
  }

  // Allow the entire breadcrumb to be altered.
  backdrop_alter('easy_breadcrumb_breadcrumb', $breadcrumb);

  return $breadcrumb;
}

/**
 * Obtain the title of the front page.
 *
 * @return string
 *   The front-page's title.
 */
function _easy_breadcrumb_obtain_home_title() {
  $front_text = config_get('easy_breadcrumb.settings', 'home_title');
  if (isset($front_text) && $front_text !== '') {
    $front_text = t($front_text);
  }
  else {
    $front_text = t('Home');
  }
  return $front_text;
}

/**
 * Obtain the title of the page.
 *
 * @param string $page_text
 *   Raw text to be use as fallback to infer the page's title.
 *
 * @return string
 *   the page's title.
 */
function _easy_breadcrumb_obtain_page_title($page_text) {
  $use_page_title_when_available = config_get('easy_breadcrumb.settings', 'title_from_page');
  // Tries to get the title of the current page (if available).
  if ($use_page_title_when_available) {
    $title = backdrop_get_title();
  }
  // Just deduce the title from the given fallback.
  if (!isset($title) || $title === '') {
    $title = _easy_breadcrumb_normalize_text($page_text);
  }
  return $title;
}

/**
 * Build a breadcrumb item.
 *
 * @param string $item_title
 *   title of the item.
 * @param array $item_classes
 *   classes.
 * @param string $item_url
 *   url of the item.
 * @param boolean $as_link
 *   denotes if the item is an url or plain text.
 *
 * @return array
 *   the generated breadcrumb item.
 */
function _easy_breadcrumb_build_item($item_title, array $item_classes, $item_url, $as_link = TRUE) {
  $config = config('easy_breadcrumb.settings');

  if ($config->get('html')) {
    $item_title = filter_xss($item_title);
  }

  if ($config->get('truncate_mode')) {
    $length = $config->get('truncate_length');
    $dots = $config->get('truncate_dots');
    $item_title = truncate_utf8($item_title, $length, TRUE, $dots);
  }

  if (!$config->get('html')) {
    $item_title = strip_tags(html_entity_decode($item_title));
    $item['html'] = TRUE;
  }

  $item = array(
    'class' => $item_classes,
    'html' => TRUE,
    'content' => $item_title,
  );

  if ($as_link) {
    $item['url'] = $item_url;
  }

  return $item;
}

/**
 * Check if the given segment is a valid path.
 *
 * @param string $segment_path
 *   path of the segment.
 *
 * @return bool
 *   true if the segment is a valid path, false otherwise.
 */
function _easy_breadcrumb_validate_segment_path($segment_path) {
  $is_valid_path = backdrop_valid_path($segment_path);

  return $is_valid_path;
}

/**
 * Check if the title should be replaced.
 *
 * @param string $segment_title
 *   Segment's title by reference.
 *
 * @return mix
 *   String with segment title if necessary or FALSE otherwise.
 */
function _easy_breadcrumb_check_replaced_title(&$segment_title) {
  $replaced_titles = config_get('easy_breadcrumb.settings', 'replaced_titles');

  if (empty($replaced_titles)) {
    return FALSE;
  }

  $map_values = preg_split('/[\r\n]/', $replaced_titles);

  foreach ($map_values as $map_value) {
    $values = explode("::", $map_value);
    if (count($values) == 2) {
      $replaced_titles_values[$values[0]] = $values[1];
    }
  }

  _easy_breadcrumb_apply_title_replacement($segment_title, $replaced_titles_values);

}

/**
 * Verifies if the given path should be exclude from the breadcrumb.
 *
 * @param string $url
 *   URL to be verified.
 *
 * @return boolean
 *   TRUE if should be excluded, FALSE otherwise.
 */
function _easy_breadcrumb_check_excluded_path($url) {
  // List of path to be excluded while generating segments.
  $excluded_paths_arr = config_get('easy_breadcrumb.settings', 'excluded_paths');
  $excluded = FALSE;
  foreach ($excluded_paths_arr as $excluded_path) {
    $exlusion_pattern = '@^' . $excluded_path . '$@';
    $excluded = preg_match($exlusion_pattern, $url);
    if ($excluded) {
      break;
    }
  }

  backdrop_alter('easy_breadcrumb_exclude_path', $excluded, $url);

  return $excluded;
}

/**
 * Obtain the title of the given segment.
 *
 * @param string $normal_path
 *   Segment's normal path.
 * @param string $valid_path
 *   Flag if the URL of the segment if valid.
 * @param string $segment_text
 *   Raw text to be used as fallback to infer the segment's title.
 *
 * @return string
 *   segment title.
 */
function _easy_breadcrumb_obtain_segment_title($normal_path, $valid_path, $segment_text) {
  // If path is valid then try to obtain the title from the menu router (if available).
  if ($valid_path) {
    $router_item = menu_get_item($normal_path);
    // If not using segment text as title then use the menu router title.
    if (!config_get('easy_breadcrumb.settings', 'segment_url_text')) {
      $title = $router_item['title'];
    }
  }
  // Just infer the title from the segment text.
  if (!isset($title) || $title === '') {
    $title = _easy_breadcrumb_normalize_text($segment_text);
  }
  return $title;
}

/**
 * Normalizes a text. E.g., transforms "about-us" to "About Us" or "About us", according to parameters.
 *
 * @param string $raw_text
 *   text to be normalized.
 *
 * @return string
 *   normalized title.
 */
function _easy_breadcrumb_normalize_text($raw_text) {
  // Filter the raw text against XSS.
  $normalized_text = check_url($raw_text);
  // Transforms '-hello--world_javascript-' on 'hello world javascript'.
  $normalized_text = str_replace(array('-', '_'), ' ', $normalized_text);
  $normalized_text = trim($normalized_text);
  $normalized_text = preg_replace('/\s{2,}/', ' ', $normalized_text);

  $config = config('easy_breadcrumb.settings');
  // Gets the flag saying the capitalizator mode.
  $capitalizator_mode = $config->get('caps_mode');
  if ($capitalizator_mode === 'ucwords') {
    // Transforms the text 'your first post' to 'Your First Post'.
    // List of words to be ignored by the capitalizator.
    $ignored_words = $config->get('caps_ignored_words');
    $words_arr = explode(' ', $normalized_text);
    // Transforms the non-ignored words of the segment.
    $words_arr[0] = backdrop_ucfirst($words_arr[0]);
    for ($idx_1 = 1, $words_quantity = count($words_arr); $idx_1 < $words_quantity; ++$idx_1) {
      // Transforms this word only if it is not in the list of ignored words.
      if (!isset($ignored_words[$words_arr[$idx_1]])) {
        $words_arr[$idx_1] = backdrop_ucfirst($words_arr[$idx_1]);
      }
    }
    $normalized_text = join(' ', $words_arr);
  }
  elseif ($capitalizator_mode === 'ucall') {
    // Transforms the text 'your first post' to 'YOUR FIRST POST'
    $normalized_text = backdrop_strtoupper($normalized_text);
  }
  elseif ($capitalizator_mode === 'ucforce') {
    // Transforms the text 'your first post' to 'your first POST'
    // List of words to be forced by the capitalizator.
    $forced_words = $config->get('caps_forced_words');
    // If case sensitivity is false make all the forced words uncapitalized by default.
    if (!$config->get('caps_forced_case')) {
      $forced_words = array_map('backdrop_strtolower', $forced_words);
    }
    $words_arr = explode(' ', $normalized_text);
    // Transforms the non-ignored words of the segment.
    if ($config->get('caps_forced_first')) {
      $words_arr[0] = backdrop_ucfirst($words_arr[0]);
    }
    for ($idx_1 = 0, $words_quantity = count($words_arr); $idx_1 < $words_quantity; ++$idx_1) {
    // If case sensitivity is false make the compared word uncapitalized in order to allow the comparison well.
      if (!$config->get('caps_forced_case')) {
        $selected_word = backdrop_strtolower($words_arr[$idx_1]);
      }
      else {
        $selected_word = $words_arr[$idx_1];
      }
      // Transforms this word only if it is in the list of forced words.
      if (in_array($selected_word, $forced_words)) {
        $words_arr[$idx_1] = backdrop_strtoupper($selected_word);
      }
    }
    $normalized_text = join(' ', $words_arr);
  }
  else {
    // Transforms the text 'your first post' to 'Your first post' (ucfirst).
    $normalized_text = backdrop_ucfirst($normalized_text);
  }

  return $normalized_text;
}

/**
 * Apply title replacements.
 *
 * @param String $title
 *   Page title.
 *
 * @param Array $replacements.
 *   Replacement rules map.
 */
function _easy_breadcrumb_apply_title_replacement(&$title, $replacements) {
  if (!is_string($title)) return;

  if (array_key_exists($title, $replacements)) {
    $title = $replacements[$title];
  }
}
